export const REDIS_MODULE_OPTIONS = Symbol('REDIS_MODULE_OPTIONS');
export const REDIS_CLIENT = Symbol('REDIS_CLIENT');

export enum FILESG_REDIS_CLIENT {
  EXPRESS_SESSION = 'EXPRESS_SESSION',
  USER = 'USER',
  FILE_SESSION = 'FILE_SESSION',
  WIDGET_SESSION = 'WIDGET_SESSION',
  OTP = 'OTP',
  OA_DID_RESOLUTION = 'OA_DID_RESOLUTION',
  FAILED_NOTIFICATION_REPORT = 'FAILED_NOTIFICATION_REPORT',
  SES_NOTIFICATION_DELIVERY = 'SES_NOTIFICATION_DELIVERY',
  CORPPASS_AGENCY = 'CORPPASS_AGENCY',
}

export enum FILESG_REDIS_NAMESPACE {
  FILE_UPLOAD_INFO = 'file-upload-info',
}
