include:
  - local: .gitlab-ci/COMMON.gitlab-ci.yml

static-files-assets-deploy-dev:
  extends: .static-files-assets-deploy-dev
  stage: deploy-to-dev-env
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: preparation

static-files-assets-deploy-stg:
  extends: .static-files-assets-deploy-stg
  stage: deploy-to-stg-env
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: preparation

static-files-assets-deploy-uat:
  extends: .static-files-assets-deploy-uat
  stage: deploy-to-uat-env
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: preparation

static-files-assets-deploy-prd:
  extends: .static-files-assets-deploy-prd
  stage: deploy-to-prd-env
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: preparation
    - job: static-files-assets-deploy-stg
