INSERT INTO activity (`id`, `uuid`, `status`, `type`, `transactionId`, `userId`, `parentId`) VALUES (4, 'activity-uuid-4', 'completed', 'receive_transfer', 1, 1, 1);

INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (5, 'fileAsset-uuid-5', 'file-1.oa', 'XXXXX', 'oa', 'uploaded', 1234, 'active', '{"data": "ok"}', 3, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (6, 'fileAsset-uuid-6', 'file-2.jpg', 'XXXXX', 'jpg', 'uploaded', 5678, 'active', '{"data": "ok"}', 3, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (7, 'fileAsset-uuid-7', 'file-1.oa', 'XXXXX', 'oa', 'uploaded', 1234, 'active', '{"data": "ok"}', 3, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (8, 'fileAsset-uuid-8', 'file-2.jpg', 'XXXXX', 'jpg', 'uploaded', 5678, 'active', '{"data": "ok"}', 3, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (9, 'fileAsset-uuid-9', 'file-1.oa', 'XXXXX', 'oa', 'uploaded', 1234, 'active', '{"data": "ok"}', 3, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (10, 'fileAsset-uuid-10', 'file-2.jpg', 'XXXXX', 'jpg', 'uploaded', 5678, 'active', '{"data": "ok"}', 3, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (11, 'fileAsset-uuid-11', 'file-1.oa', 'XXXXX', 'oa', 'uploaded', 1234, 'active', '{"data": "ok"}', 3, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (12, 'fileAsset-uuid-12', 'file-2.jpg', 'XXXXX', 'jpg', 'uploaded', 5678, 'active', '{"data": "ok"}', 3, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (13, 'fileAsset-uuid-13', 'file-1.oa', 'XXXXX', 'oa', 'uploaded', 1234, 'active', '{"data": "ok"}', 3, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (14, 'fileAsset-uuid-14', 'file-2.jpg', 'XXXXX', 'jpg', 'uploaded', 5678, 'active', '{"data": "ok"}', 3, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (15, 'fileAsset-uuid-15', 'file-1.oa', 'XXXXX', 'oa', 'uploaded', 1234, 'active', '{"data": "ok"}', 3, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (16, 'fileAsset-uuid-16', 'file-2.jpg', 'XXXXX', 'jpg', 'uploaded', 5678, 'active', '{"data": "ok"}', 3, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (17, 'fileAsset-uuid-17', 'file-1.oa', 'XXXXX', 'oa', 'uploaded', 1234, 'active', '{"data": "ok"}', 3, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (18, 'fileAsset-uuid-18', 'file-2.jpg', 'XXXXX', 'jpg', 'uploaded', 5678, 'active', '{"data": "ok"}', 3, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (19, 'fileAsset-uuid-19', 'file-1.oa', 'XXXXX', 'oa', 'uploaded', 1234, 'active', '{"data": "ok"}', 3, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (20, 'fileAsset-uuid-20', 'file-2.jpg', 'XXXXX', 'jpg', 'uploaded', 5678, 'active', '{"data": "ok"}', 3, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (21, 'fileAsset-uuid-21', 'file-1.oa', 'XXXXX', 'oa', 'uploaded', 1234, 'active', '{"data": "ok"}', 3, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (22, 'fileAsset-uuid-22', 'file-2.jpg', 'XXXXX', 'jpg', 'uploaded', 5678, 'active', '{"data": "ok"}', 3, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (23, 'fileAsset-uuid-23', 'file-1.oa', 'XXXXX', 'oa', 'uploaded', 1234, 'active', '{"data": "ok"}', 3, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (24, 'fileAsset-uuid-24', 'file-2.jpg', 'XXXXX', 'jpg', 'uploaded', 5678, 'active', '{"data": "ok"}', 3, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (25, 'fileAsset-uuid-25', 'file-1.oa', 'XXXXX', 'oa', 'uploaded', 1234, 'active', '{"data": "ok"}', 3, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (26, 'fileAsset-uuid-26', 'file-2.jpg', 'XXXXX', 'jpg', 'uploaded', 5678, 'active', '{"data": "ok"}', 3, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (27, 'fileAsset-uuid-27', 'file-1.oa', 'XXXXX', 'oa', 'uploaded', 1234, 'active', '{"data": "ok"}', 3, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (28, 'fileAsset-uuid-28', 'file-2.jpg', 'XXXXX', 'jpg', 'uploaded', 5678, 'active', '{"data": "ok"}', 3, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (29, 'fileAsset-uuid-29', 'file-1.oa', 'XXXXX', 'oa', 'uploaded', 1234, 'active', '{"data": "ok"}', 3, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (30, 'fileAsset-uuid-30', 'file-2.jpg', 'XXXXX', 'jpg', 'uploaded', 5678, 'active', '{"data": "ok"}', 3, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (31, 'fileAsset-uuid-31', 'file-1.oa', 'XXXXX', 'oa', 'uploaded', 1234, 'active', '{"data": "ok"}', 3, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (32, 'fileAsset-uuid-32', 'file-2.jpg', 'XXXXX', 'jpg', 'uploaded', 5678, 'active', '{"data": "ok"}', 3, 3);


INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (33, 'fileAsset-uuid-33', 'file-1.oa', 'XXXXX', 'oa', 'transferred', 1234, 'active', '{"data": "ok"}', 1, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (34, 'fileAsset-uuid-34', 'file-2.jpg', 'XXXXX', 'jpg', 'transferred', 5678, 'active', '{"data": "ok"}', 1, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (35, 'fileAsset-uuid-35', 'file-1.oa', 'XXXXX', 'oa', 'transferred', 1234, 'active', '{"data": "ok"}', 1, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (36, 'fileAsset-uuid-36', 'file-2.jpg', 'XXXXX', 'jpg', 'transferred', 5678, 'active', '{"data": "ok"}', 1, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (37, 'fileAsset-uuid-37', 'file-1.oa', 'XXXXX', 'oa', 'transferred', 1234, 'active', '{"data": "ok"}', 1, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (38, 'fileAsset-uuid-38', 'file-2.jpg', 'XXXXX', 'jpg', 'transferred', 5678, 'active', '{"data": "ok"}', 1, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (39, 'fileAsset-uuid-39', 'file-1.oa', 'XXXXX', 'oa', 'transferred', 1234, 'active', '{"data": "ok"}', 1, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (40, 'fileAsset-uuid-40', 'file-2.jpg', 'XXXXX', 'jpg', 'transferred', 5678, 'active', '{"data": "ok"}', 1, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (41, 'fileAsset-uuid-41', 'file-1.oa', 'XXXXX', 'oa', 'transferred', 1234, 'active', '{"data": "ok"}', 1, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (42, 'fileAsset-uuid-42', 'file-2.jpg', 'XXXXX', 'jpg', 'transferred', 5678, 'active', '{"data": "ok"}', 1, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (43, 'fileAsset-uuid-43', 'file-1.oa', 'XXXXX', 'oa', 'transferred', 1234, 'active', '{"data": "ok"}', 1, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (44, 'fileAsset-uuid-44', 'file-2.jpg', 'XXXXX', 'jpg', 'transferred', 5678, 'active', '{"data": "ok"}', 1, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (45, 'fileAsset-uuid-45', 'file-1.oa', 'XXXXX', 'oa', 'transferred', 1234, 'active', '{"data": "ok"}', 1, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (46, 'fileAsset-uuid-46', 'file-2.jpg', 'XXXXX', 'jpg', 'transferred', 5678, 'active', '{"data": "ok"}', 1, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (47, 'fileAsset-uuid-47', 'file-1.oa', 'XXXXX', 'oa', 'transferred', 1234, 'active', '{"data": "ok"}', 1, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (48, 'fileAsset-uuid-48', 'file-2.jpg', 'XXXXX', 'jpg', 'transferred', 5678, 'active', '{"data": "ok"}', 1, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (49, 'fileAsset-uuid-49', 'file-1.oa', 'XXXXX', 'oa', 'transferred', 1234, 'active', '{"data": "ok"}', 1, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (50, 'fileAsset-uuid-50', 'file-2.jpg', 'XXXXX', 'jpg', 'transferred', 5678, 'active', '{"data": "ok"}', 1, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (51, 'fileAsset-uuid-51', 'file-1.oa', 'XXXXX', 'oa', 'transferred', 1234, 'active', '{"data": "ok"}', 1, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (52, 'fileAsset-uuid-52', 'file-2.jpg', 'XXXXX', 'jpg', 'transferred', 5678, 'active', '{"data": "ok"}', 1, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (53, 'fileAsset-uuid-53', 'file-1.oa', 'XXXXX', 'oa', 'transferred', 1234, 'active', '{"data": "ok"}', 1, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (54, 'fileAsset-uuid-54', 'file-2.jpg', 'XXXXX', 'jpg', 'transferred', 5678, 'active', '{"data": "ok"}', 1, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (55, 'fileAsset-uuid-55', 'file-1.oa', 'XXXXX', 'oa', 'transferred', 1234, 'active', '{"data": "ok"}', 1, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (56, 'fileAsset-uuid-56', 'file-2.jpg', 'XXXXX', 'jpg', 'transferred', 5678, 'active', '{"data": "ok"}', 1, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (57, 'fileAsset-uuid-57', 'file-1.oa', 'XXXXX', 'oa', 'transferred', 1234, 'active', '{"data": "ok"}', 1, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (58, 'fileAsset-uuid-58', 'file-2.jpg', 'XXXXX', 'jpg', 'transferred', 5678, 'active', '{"data": "ok"}', 1, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (59, 'fileAsset-uuid-59', 'file-1.oa', 'XXXXX', 'oa', 'transferred', 1234, 'active', '{"data": "ok"}', 1, 3);
INSERT INTO file_asset (`id`, `uuid`, `name`, `documentHash`, `documentType`, `type`, `size`, `status`, `metadata`, `ownerId`, `issuerId`) VALUES (60, 'fileAsset-uuid-60', 'file-2.jpg', 'XXXXX', 'jpg', 'transferred', 5678, 'active', '{"data": "ok"}', 1, 3);


INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (1, 5);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (1, 6);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (1, 7);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (1, 8);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (1, 9);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (1, 10);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (1, 11);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (1, 12);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (1, 13);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (1, 14);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (1, 15);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (1, 16);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (1, 17);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (1, 18);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (1, 19);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (1, 20);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (1, 21);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (1, 22);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (1, 23);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (1, 24);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (1, 25);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (1, 26);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (1, 27);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (1, 28);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (1, 29);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (1, 30);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (1, 31);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (1, 32);

INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (2, 5);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (2, 6);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (2, 7);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (2, 8);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (2, 9);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (2, 10);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (2, 11);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (2, 12);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (2, 13);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (2, 14);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (2, 15);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (2, 16);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (2, 17);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (2, 18);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (2, 19);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (2, 20);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (2, 21);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (2, 22);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (2, 23);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (2, 24);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (2, 25);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (2, 26);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (2, 27);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (2, 28);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (2, 29);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (2, 30);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (2, 31);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (2, 32);

INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (4, 33);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (4, 34);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (4, 35);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (4, 36);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (4, 37);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (4, 38);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (4, 39);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (4, 40);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (4, 41);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (4, 42);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (4, 43);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (4, 44);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (4, 45);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (4, 46);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (4, 47);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (4, 48);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (4, 49);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (4, 50);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (4, 51);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (4, 52);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (4, 53);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (4, 54);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (4, 55);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (4, 56);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (4, 57);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (4, 58);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (4, 59);
INSERT INTO activity_file (`activityId`, `fileAssetId`) VALUES (4, 60);
