include:
  - local: .gitlab-ci/COMMON.gitlab-ci.yml

frontend-maintenance-page-deploy-dev:
  extends: .frontend-maintenance-page-deploy-dev
  stage: deploy-to-dev-env
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: preparation
    - pipeline: $PARENT_PIPELINE_ID
      job: frontend-maintenance-page-build

frontend-maintenance-page-deploy-stg:
  extends: .frontend-maintenance-page-deploy-stg
  stage: deploy-to-stg-env
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: preparation
    - pipeline: $PARENT_PIPELINE_ID
      job: frontend-maintenance-page-build

frontend-maintenance-page-deploy-uat:
  extends: .frontend-maintenance-page-deploy-uat
  stage: deploy-to-uat-env
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: preparation
    - pipeline: $PARENT_PIPELINE_ID
      job: frontend-maintenance-page-build

frontend-maintenance-page-deploy-prd:
  extends: .frontend-maintenance-page-deploy-prd
  stage: deploy-to-prd-env
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: preparation
    - pipeline: $PARENT_PIPELINE_ID
      job: frontend-maintenance-page-build
    - job: frontend-maintenance-page-deploy-stg
